- hosts: all
  vars:
    sudoers:
      - martin
  tasks:
    - name: Make sure we have a 'wheel' group
      become: true
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      become: true
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Add sudoers users to wheel group
      become: true
      user:
        name: "{{ item }}"
        groups: wheel
        append: yes
      with_items: "{{ sudoers }}"